INSERT INTO `Product` (`eid`, `description`) VALUES
(1,	'stethoscope'),
(2,	'scalpel'),
(3,	'blanket'),
(4,	'bedsheet'),
(5,	'towel'),
(6,	'X-ray film'),
(7,	'clipboard'),
(8,	'blank medical chart'),
(9,	'pipette'),
(10,	'test tube'),
(11,	'saline solution'),
(12,	'type O- blood'),
(13,	'meal tray'),
(14,	'linen bandage'),
(15,	'plaster bandage'),
(16,	'paper cup'),
(17,	'hospital robe'),
(18,	'soap'),
(19,	'cleaning fluid');
